### ISSUE TITLE
crash on flux's GitRepository crd

### ISSUE THREAD

**Issue by clux** [kube-rs/kopium#81]
output:

```rust
#![allow(non_snake_case)]

use kube::CustomResource;
use serde::{Serialize, Deserialize};
use std::collections::BTreeMap;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(group = "source.toolkit.fluxcd.io", version = "v1beta2", kind = "GitRepository", plural = "gitrepositories")]
#[kube(namespaced)]
#[kube(status = "GitRepositoryStatus")]
#[kube(schema = "disabled")]
pub struct GitRepositorySpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accessFrom: Option<GitRepositoryAccessFrom>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gitImplementation: Option<GitRepositoryGitImplementation>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ignore: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include: Option<Vec<GitRepositoryInclude>>,
    pub interval: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recurseSubmodules: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<GitRepositoryRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secretRef: Option<GitRepositorySecretRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suspend: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    pub url: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verify: Option<GitRepositoryVerify>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GitRepositoryAccessFrom {
    pub namespaceSelectors: Vec<GitRepositoryAccessFromNamespaceSelectors>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GitRepositoryAccessFromNamespaceSelectors {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub matchLabels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum GitRepositoryGitImplementation {
thread 'main' panicked at '"go-git" is not a valid Ident', /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.42/src/fallback.rs:730:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: proc_macro2::fallback::validate_ident
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.42/src/fallback.rs:730:9
   3: proc_macro2::fallback::Ident::_new
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.42/src/fallback.rs:672:9
   4: proc_macro2::fallback::Ident::new
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.42/src/fallback.rs:682:9
   5: proc_macro2::imp::Ident::new
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.42/src/wrapper.rs:685:50
   6: proc_macro2::Ident::new
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.42/src/lib.rs:953:21
   7: quote::__private::ident_maybe_raw
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.20/src/runtime.rs:391:9
   8: quote::__private::mk_ident
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.20/src/runtime.rs:384:5
   9: kopium::Kopium::generate::{{closure}}
             at /home/clux/kube/kopium/src/main.rs:246:29
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  11: kopium::Kopium::dispatch::{{closure}}
             at /home/clux/kube/kopium/src/main.rs:158:31
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  13: kopium::main::{{closure}}
             at /home/clux/kube/kopium/src/main.rs:130:20
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  15: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:54
  16: tokio::coop::with_budget::{{closure}}
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  18: std::thread::local::LocalKey<T>::with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  19: tokio::coop::with_budget
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
  20: tokio::coop::budget
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  21: tokio::park::thread::CachedParkThread::block_on
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:31
  22: tokio::runtime::enter::Enter::block_on
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/enter.rs:152:13
  23: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/mod.rs:90:9
  24: tokio::runtime::Runtime::block_on
             at /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/mod.rs:484:43
  25: kopium::main
             at /home/clux/kube/kopium/src/main.rs:130:5
  26: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

after trying to output a member from:
```yaml
              gitImplementation:
                default: go-git
                description: Determines which git client library to use. Defaults
                  to go-git, valid values are ('go-git', 'libgit2').
                enum:
                - go-git
                - libgit2
                type: string
```

at the printing stage because of a dash in an ident. need to rename dashes to underscores and preserve these.

**Comment by clux** [comment]
Workaround: run kopium with `-z` (or -A) to force renames to snake-case.

**Comment by clux** [comment]
Interestingly, this may imply that using go or json style keys as rust members is unsound anyway and we should always be doing the snake_case conversion :thinking:
